#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

# echo "exec rake import_leagues RAILS_ENV=${RAILS_ENV:-production}"
# bundle exec rake import_leagues RAILS_ENV=${RAILS_ENV:-production}